name: Comprobaciones

on:
  push:
    branches: [main]
  pull_request:

jobs:
  prueba:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - name: Ejecutar la comprobación
        run: python prueba.py
